# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4edc98845cab3a2a35b4cb5238ad5e4b2701ff409b2b948b3fe510a575a07d08f7af891f03fedee0109e371e40b6b91545e972cfb375e2036326eaf490c1df59

test:
  secret_key_base: 4e47af3f7e29660c24a8d92837f6331d3ef6b17ee6dca872ad84e2ff851e568b2fc0826fb9b988476d6a0e3a06598e6809bb6f287230f9c39c5231d188ad8969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
